CREATE TABLE `airports`(
  `id` INT AUTO_INCREMENT PRIMARY KEY
  ,`name` varchar(100) NOT NULL
  ,`iata_code` varchar(4) NOT NULL UNIQUE
  ,`country_iso2` char(2) NOT NULL
  ,CONSTRAINT `fk_airports_country_iso2` FOREIGN KEY (`country_iso2`) REFERENCES `countries` (`iso2`)
  ,INDEX idx_airports_iata_code (iata_code)
);

INSERT INTO `airports` VALUES (NULL,'Betong International Airport','BTZ','TH');
INSERT INTO `airports` VALUES (NULL,'Banyuwangi International Airport','BWX','ID');
INSERT INTO `airports` VALUES (NULL,'Bicol International Airport','LGP','PH');
INSERT INTO `airports` VALUES (NULL,'Laguindingan International Airport','CGY','PH');
INSERT INTO `airports` VALUES (NULL,'Cagayan North International Airport','LLC','PH');
INSERT INTO `airports` VALUES (NULL,'Narita International Airport','NRT','JP');
INSERT INTO `airports` VALUES (NULL,'Kansai International Airport','KIX','JP');
INSERT INTO `airports` VALUES (NULL,'Chubu Centrair International Airport','NGO','JP');
INSERT INTO `airports` VALUES (NULL,'Osaka International Airport','ITM','JP');
INSERT INTO `airports` VALUES (NULL,'Tokyo Haneda International Airport','HND','JP');
INSERT INTO `airports` VALUES (NULL,'Rosella Plains Airport','RLP','AU');
INSERT INTO `airports` VALUES (NULL,'Diosdado Macapagal International Airport','CRK','PH');
INSERT INTO `airports` VALUES (NULL,'Laoag International Airport','LAO','PH');
INSERT INTO `airports` VALUES (NULL,'Ninoy Aquino International Airport','MNL','PH');
INSERT INTO `airports` VALUES (NULL,'General Santos International Airport','GES','PH');
INSERT INTO `airports` VALUES (NULL,'Zamboanga International Airport','ZAM','PH');
INSERT INTO `airports` VALUES (NULL,'Bohol-Panglao International Airport','TAG','PH');
INSERT INTO `airports` VALUES (NULL,'Iloilo International Airport','ILO','PH');
INSERT INTO `airports` VALUES (NULL,'Kalibo International Airport','KLO','PH');
INSERT INTO `airports` VALUES (NULL,'Mactan Cebu International Airport','CEB','PH');
INSERT INTO `airports` VALUES (NULL,'Western Sydney International (Nancy Bird Walton) Airport','SWZ','AU');
INSERT INTO `airports` VALUES (NULL,'Don Mueang International Airport','DMK','TH');
INSERT INTO `airports` VALUES (NULL,'U-Tapao International Airport','UTP','TH');
INSERT INTO `airports` VALUES (NULL,'Chiang Mai International Airport','CNX','TH');
INSERT INTO `airports` VALUES (NULL,'Mae Fah Luang - Chiang Rai International Airport','CEI','TH');
INSERT INTO `airports` VALUES (NULL,'Phuket International Airport','HKT','TH');
INSERT INTO `airports` VALUES (NULL,'Hat Yai International Airport','HDY','TH');
INSERT INTO `airports` VALUES (NULL,'Hasanuddin International Airport','UPG','ID');
INSERT INTO `airports` VALUES (NULL,'Ngurah Rai (Bali) International Airport','DPS','ID');
INSERT INTO `airports` VALUES (NULL,'Lombok International Airport','LOP','ID');
INSERT INTO `airports` VALUES (NULL,'Yogyakarta International Airport','YIA','ID');
INSERT INTO `airports` VALUES (NULL,'Sentani International Airport','DJJ','ID');
INSERT INTO `airports` VALUES (NULL,'Aji Pangeran Tumenggung Pranoto International Airport','AAP','ID');
INSERT INTO `airports` VALUES (NULL,'Adisutjipto International Airport','JOG','ID');
INSERT INTO `airports` VALUES (NULL,'Adisumarmo International Airport','SOC','ID');
INSERT INTO `airports` VALUES (NULL,'Juanda International Airport','SUB','ID');
INSERT INTO `airports` VALUES (NULL,'Kuching International Airport','KCH','MY');
INSERT INTO `airports` VALUES (NULL,'Kota Kinabalu International Airport','BKI','MY');
INSERT INTO `airports` VALUES (NULL,'Kertajati International Airport','KJT','ID');
INSERT INTO `airports` VALUES (NULL,'Hang Nadim International Airport','BTH','ID');
INSERT INTO `airports` VALUES (NULL,'Raja Haji Fisabilillah International Airport','TNJ','ID');
INSERT INTO `airports` VALUES (NULL,'Halim Perdanakusuma International Airport','HLP','ID');
INSERT INTO `airports` VALUES (NULL,'Soekarno-Hatta International Airport','CGK','ID');
INSERT INTO `airports` VALUES (NULL,'Radin Inten II International Airport','TKG','ID');
INSERT INTO `airports` VALUES (NULL,'Kualanamu International Airport','KNO','ID');
INSERT INTO `airports` VALUES (NULL,'H A S Hanandjoeddin International Airport','TJQ','ID');
INSERT INTO `airports` VALUES (NULL,'Minangkabau International Airport','PDG','ID');
INSERT INTO `airports` VALUES (NULL,'Sultan Iskandar Muda International Airport','BTJ','ID');
INSERT INTO `airports` VALUES (NULL,'Senai International Airport','JHB','MY');
INSERT INTO `airports` VALUES (NULL,'Kuala Lumpur International Airport','KUL','MY');
INSERT INTO `airports` VALUES (NULL,'Langkawi International Airport','LGK','MY');
INSERT INTO `airports` VALUES (NULL,'Malacca International Airport','MKZ','MY');
INSERT INTO `airports` VALUES (NULL,'Penang International Airport','PEN','MY');
INSERT INTO `airports` VALUES (NULL,'Sultan Abdul Aziz Shah International Airport','SZB','MY');
INSERT INTO `airports` VALUES (NULL,'Brisbane International Airport','BNE','AU');
INSERT INTO `airports` VALUES (NULL,'Cairns International Airport','CNS','AU');
INSERT INTO `airports` VALUES (NULL,'Sunshine Coast Airport','MCY','AU');
INSERT INTO `airports` VALUES (NULL,'Hobart International Airport','HBA','AU');
INSERT INTO `airports` VALUES (NULL,'Launceston Airport','LST','AU');
INSERT INTO `airports` VALUES (NULL,'Melbourne International Airport','MEL','AU');
INSERT INTO `airports` VALUES (NULL,'Adelaide International Airport','ADL','AU');
INSERT INTO `airports` VALUES (NULL,'Darwin International Airport','DRW','AU');
INSERT INTO `airports` VALUES (NULL,'Port Hedland International Airport','PHE','AU');
INSERT INTO `airports` VALUES (NULL,'Perth International Airport','PER','AU');
INSERT INTO `airports` VALUES (NULL,'Sydney Bankstown Airport','BWU','AU');
INSERT INTO `airports` VALUES (NULL,'Canberra International Airport','CBR','AU');
INSERT INTO `airports` VALUES (NULL,'Newcastle Airport','NTL','AU');
INSERT INTO `airports` VALUES (NULL,'Muan International Airport','MWX','KR');
INSERT INTO `airports` VALUES (NULL,'Yangyang International Airport','YNY','KR');
INSERT INTO `airports` VALUES (NULL,'Jeju International Airport','CJU','KR');
INSERT INTO `airports` VALUES (NULL,'Gimhae International Airport','PUS','KR');
INSERT INTO `airports` VALUES (NULL,'Incheon International Airport','ICN','KR');
INSERT INTO `airports` VALUES (NULL,'Gimpo International Airport','GMP','KR');
INSERT INTO `airports` VALUES (NULL,'Kaohsiung International Airport','KHH','TW');
INSERT INTO `airports` VALUES (NULL,'Taichung International Airport','RMQ','TW');
INSERT INTO `airports` VALUES (NULL,'Tainan International Airport','TNN','TW');
INSERT INTO `airports` VALUES (NULL,'Taiwan Taoyuan International Airport','TPE','TW');
INSERT INTO `airports` VALUES (NULL,'Cat Bi International Airport','HPH','VN');
INSERT INTO `airports` VALUES (NULL,'Cam Ranh International Airport','CXR','VN');
INSERT INTO `airports` VALUES (NULL,'Can Tho International Airport','VCA','VN');
INSERT INTO `airports` VALUES (NULL,'Da Nang International Airport','DAD','VN');
INSERT INTO `airports` VALUES (NULL,'Noi Bai International Airport','HAN','VN');
INSERT INTO `airports` VALUES (NULL,'Phu Bai International Airport','HUI','VN');
INSERT INTO `airports` VALUES (NULL,'Phu Quoc International Airport','PQC','VN');
INSERT INTO `airports` VALUES (NULL,'Tan Son Nhat International Airport','SGN','VN');
INSERT INTO `airports` VALUES (NULL,'Van Don International Airport','VDO','VN');
INSERT INTO `airports` VALUES (NULL,'Lianyungang Huaguoshan International Airport','LYG','CN');
INSERT INTO `airports` VALUES (NULL,'Yantai Penglai International Airport','YNT','CN');
INSERT INTO `airports` VALUES (NULL,'Beijing Capital International Airport','PEK','CN');
INSERT INTO `airports` VALUES (NULL,'Beijing Daxing International Airport','PKX','CN');
INSERT INTO `airports` VALUES (NULL,'Hohhot Baita International Airport','HET','CN');
INSERT INTO `airports` VALUES (NULL,'Shijiazhuang Zhengding International Airport','SJW','CN');
INSERT INTO `airports` VALUES (NULL,'Tianjin Binhai International Airport','TSN','CN');
INSERT INTO `airports` VALUES (NULL,'Zhangjiajie Hehua International Airport','DYG','CN');
INSERT INTO `airports` VALUES (NULL,'Guangzhou Baiyun International Airport','CAN','CN');
INSERT INTO `airports` VALUES (NULL,'Changsha Huanghua International Airport','CSX','CN');
INSERT INTO `airports` VALUES (NULL,'Jieyang Chaoshan International Airport','SWA','CN');
INSERT INTO `airports` VALUES (NULL,'Shenzhen Bao\'an International Airport','SZX','CN');
INSERT INTO `airports` VALUES (NULL,'Zhengzhou Xinzheng International Airport','CGO','CN');
INSERT INTO `airports` VALUES (NULL,'Yinchuan Hedong International Airport','INC','CN');
INSERT INTO `airports` VALUES (NULL,'Lanzhou Zhongchuan International Airport','LHW','CN');
INSERT INTO `airports` VALUES (NULL,'Xi\'an Xianyang International Airport','XIY','CN');
INSERT INTO `airports` VALUES (NULL,'Xishuangbanna Gasa International Airport','JHG','CN');
INSERT INTO `airports` VALUES (NULL,'Nanchang Changbei International Airport','KHN','CN');
INSERT INTO `airports` VALUES (NULL,'Fuzhou Changle International Airport','FOC','CN');
INSERT INTO `airports` VALUES (NULL,'Hangzhou Xiaoshan International Airport','HGH','CN');
INSERT INTO `airports` VALUES (NULL,'Jinan Yaoqiang International Airport','TNA','CN');
INSERT INTO `airports` VALUES (NULL,'Shanghai Pudong International Airport','PVG','CN');
INSERT INTO `airports` VALUES (NULL,'Shanghai Hongqiao International Airport','SHA','CN');
INSERT INTO `airports` VALUES (NULL,'Yancheng Nanyang International Airport','YNZ','CN');
INSERT INTO `airports` VALUES (NULL,'Chongqing Jiangbei International Airport','CKG','CN');
INSERT INTO `airports` VALUES (NULL,'Chengdu Tianfu International Airport','TFU','CN');
INSERT INTO `airports` VALUES (NULL,'Chengdu Shuangliu International Airport','CTU','CN');
INSERT INTO `airports` VALUES (NULL,'Changchun Longjia International Airport','CGQ','CN');
INSERT INTO `airports` VALUES (NULL,'Harbin Taiping International Airport','HRB','CN');
INSERT INTO `airports` VALUES (NULL,'Shenyang Taoxian International Airport','SHE','CN');
INSERT INTO `airports` VALUES (NULL,'Singapore Changi Airport','SIN','SG');