REATE TABLE IF NOT EXISTS countries(
   id           INTEGER  NOT NULL PRIMARY KEY,
   name         VARCHAR(36) NOT NULL,
   iso3         VARCHAR(3) NOT NULL UNIQUE,
   iso2         VARCHAR(2) NOT NULL UNIQUE
);
INSERT INTO countries(id,name,iso3,iso2) VALUES (14,'Australia','AUS','AU');
INSERT INTO countries(id,name,iso3,iso2) VALUES (15,'Austria','AUT','AT');
INSERT INTO countries(id,name,iso3,iso2) VALUES (33,'Brunei','BRN','BN');
INSERT INTO countries(id,name,iso3,iso2) VALUES (37,'Cambodia','KHM','KH');
INSERT INTO countries(id,name,iso3,iso2) VALUES (38,'Cameroon','CMR','CM');
INSERT INTO countries(id,name,iso3,iso2) VALUES (39,'Canada','CAN','CA');
INSERT INTO countries(id,name,iso3,iso2) VALUES (40,'Cape Verde','CPV','CV');
INSERT INTO countries(id,name,iso3,iso2) VALUES (42,'Central African Republic','CAF','CF');
INSERT INTO countries(id,name,iso3,iso2) VALUES (43,'Chad','TCD','TD');
INSERT INTO countries(id,name,iso3,iso2) VALUES (44,'Chile','CHL','CL');
INSERT INTO countries(id,name,iso3,iso2) VALUES (45,'China','CHN','CN');
INSERT INTO countries(id,name,iso3,iso2) VALUES (46,'Christmas Island','CXR','CX');
INSERT INTO countries(id,name,iso3,iso2) VALUES (47,'Cocos (Keeling) Islands','CCK','CC');
INSERT INTO countries(id,name,iso3,iso2) VALUES (48,'Colombia','COL','CO');
INSERT INTO countries(id,name,iso3,iso2) VALUES (49,'Comoros','COM','KM');
INSERT INTO countries(id,name,iso3,iso2) VALUES (50,'Congo','COG','CG');
INSERT INTO countries(id,name,iso3,iso2) VALUES (52,'Cook Islands','COK','CK');
INSERT INTO countries(id,name,iso3,iso2) VALUES (53,'Costa Rica','CRI','CR');
INSERT INTO countries(id,name,iso3,iso2) VALUES (54,'Cote D''Ivoire (Ivory Coast)','CIV','CI');
INSERT INTO countries(id,name,iso3,iso2) VALUES (55,'Croatia','HRV','HR');
INSERT INTO countries(id,name,iso3,iso2) VALUES (56,'Cuba','CUB','CU');
INSERT INTO countries(id,name,iso3,iso2) VALUES (57,'Cyprus','CYP','CY');
INSERT INTO countries(id,name,iso3,iso2) VALUES (58,'Czech Republic','CZE','CZ');
INSERT INTO countries(id,name,iso3,iso2) VALUES (51,'Democratic Republic of the Congo','COD','CD');
INSERT INTO countries(id,name,iso3,iso2) VALUES (59,'Denmark','DNK','DK');
INSERT INTO countries(id,name,iso3,iso2) VALUES (60,'Djibouti','DJI','DJ');
INSERT INTO countries(id,name,iso3,iso2) VALUES (63,'East Timor','TLS','TL');
INSERT INTO countries(id,name,iso3,iso2) VALUES (64,'Ecuador','ECU','EC');
INSERT INTO countries(id,name,iso3,iso2) VALUES (65,'Egypt','EGY','EG');
INSERT INTO countries(id,name,iso3,iso2) VALUES (66,'El Salvador','SLV','SV');
INSERT INTO countries(id,name,iso3,iso2) VALUES (67,'Equatorial Guinea','GNQ','GQ');
INSERT INTO countries(id,name,iso3,iso2) VALUES (68,'Eritrea','ERI','ER');
INSERT INTO countries(id,name,iso3,iso2) VALUES (69,'Estonia','EST','EE');
INSERT INTO countries(id,name,iso3,iso2) VALUES (70,'Ethiopia','ETH','ET');
INSERT INTO countries(id,name,iso3,iso2) VALUES (71,'Falkland Islands','FLK','FK');
INSERT INTO countries(id,name,iso3,iso2) VALUES (72,'Faroe Islands','FRO','FO');
INSERT INTO countries(id,name,iso3,iso2) VALUES (73,'Fiji Islands','FJI','FJ');
INSERT INTO countries(id,name,iso3,iso2) VALUES (74,'Finland','FIN','FI');
INSERT INTO countries(id,name,iso3,iso2) VALUES (75,'France','FRA','FR');
INSERT INTO countries(id,name,iso3,iso2) VALUES (76,'French Guiana','GUF','GF');
INSERT INTO countries(id,name,iso3,iso2) VALUES (77,'French Polynesia','PYF','PF');
INSERT INTO countries(id,name,iso3,iso2) VALUES (78,'French Southern Territories','ATF','TF');
INSERT INTO countries(id,name,iso3,iso2) VALUES (79,'Gabon','GAB','GA');
INSERT INTO countries(id,name,iso3,iso2) VALUES (80,'Gambia The','GMB','GM');
INSERT INTO countries(id,name,iso3,iso2) VALUES (81,'Georgia','GEO','GE');
INSERT INTO countries(id,name,iso3,iso2) VALUES (82,'Germany','DEU','DE');
INSERT INTO countries(id,name,iso3,iso2) VALUES (83,'Ghana','GHA','GH');
INSERT INTO countries(id,name,iso3,iso2) VALUES (84,'Gibraltar','GIB','GI');
INSERT INTO countries(id,name,iso3,iso2) VALUES (85,'Greece','GRC','GR');
INSERT INTO countries(id,name,iso3,iso2) VALUES (86,'Greenland','GRL','GL');
INSERT INTO countries(id,name,iso3,iso2) VALUES (88,'Guadeloupe','GLP','GP');
INSERT INTO countries(id,name,iso3,iso2) VALUES (90,'Guatemala','GTM','GT');
INSERT INTO countries(id,name,iso3,iso2) VALUES (92,'Guinea','GIN','GN');
INSERT INTO countries(id,name,iso3,iso2) VALUES (93,'Guinea-Bissau','GNB','GW');
INSERT INTO countries(id,name,iso3,iso2) VALUES (94,'Guyana','GUY','GY');
INSERT INTO countries(id,name,iso3,iso2) VALUES (95,'Haiti','HTI','HT');
INSERT INTO countries(id,name,iso3,iso2) VALUES (96,'Heard Island and McDonald Islands','HMD','HM');
INSERT INTO countries(id,name,iso3,iso2) VALUES (97,'Honduras','HND','HN');
INSERT INTO countries(id,name,iso3,iso2) VALUES (98,'Hong Kong S.A.R.','HKG','HK');
INSERT INTO countries(id,name,iso3,iso2) VALUES (99,'Hungary','HUN','HU');
INSERT INTO countries(id,name,iso3,iso2) VALUES (100,'Iceland','ISL','IS');
INSERT INTO countries(id,name,iso3,iso2) VALUES (101,'India','IND','IN');
INSERT INTO countries(id,name,iso3,iso2) VALUES (102,'Indonesia','IDN','ID');
INSERT INTO countries(id,name,iso3,iso2) VALUES (103,'Iran','IRN','IR');
INSERT INTO countries(id,name,iso3,iso2) VALUES (104,'Iraq','IRQ','IQ');
INSERT INTO countries(id,name,iso3,iso2) VALUES (105,'Ireland','IRL','IE');
INSERT INTO countries(id,name,iso3,iso2) VALUES (106,'Israel','ISR','IL');
INSERT INTO countries(id,name,iso3,iso2) VALUES (107,'Italy','ITA','IT');
INSERT INTO countries(id,name,iso3,iso2) VALUES (108,'Jamaica','JAM','JM');
INSERT INTO countries(id,name,iso3,iso2) VALUES (109,'Japan','JPN','JP');
INSERT INTO countries(id,name,iso3,iso2) VALUES (110,'Jersey','JEY','JE');
INSERT INTO countries(id,name,iso3,iso2) VALUES (111,'Jordan','JOR','JO');
INSERT INTO countries(id,name,iso3,iso2) VALUES (112,'Kazakhstan','KAZ','KZ');
INSERT INTO countries(id,name,iso3,iso2) VALUES (113,'Kenya','KEN','KE');
INSERT INTO countries(id,name,iso3,iso2) VALUES (114,'Kiribati','KIR','KI');
INSERT INTO countries(id,name,iso3,iso2) VALUES (248,'Kosovo','XKX','XK');
INSERT INTO countries(id,name,iso3,iso2) VALUES (117,'Kuwait','KWT','KW');
INSERT INTO countries(id,name,iso3,iso2) VALUES (118,'Kyrgyzstan','KGZ','KG');
INSERT INTO countries(id,name,iso3,iso2) VALUES (119,'Laos','LAO','LA');
INSERT INTO countries(id,name,iso3,iso2) VALUES (120,'Latvia','LVA','LV');
INSERT INTO countries(id,name,iso3,iso2) VALUES (121,'Lebanon','LBN','LB');
INSERT INTO countries(id,name,iso3,iso2) VALUES (122,'Lesotho','LSO','LS');
INSERT INTO countries(id,name,iso3,iso2) VALUES (123,'Liberia','LBR','LR');
INSERT INTO countries(id,name,iso3,iso2) VALUES (124,'Libya','LBY','LY');
INSERT INTO countries(id,name,iso3,iso2) VALUES (125,'Liechtenstein','LIE','LI');
INSERT INTO countries(id,name,iso3,iso2) VALUES (126,'Lithuania','LTU','LT');
INSERT INTO countries(id,name,iso3,iso2) VALUES (127,'Luxembourg','LUX','LU');
INSERT INTO countries(id,name,iso3,iso2) VALUES (128,'Macau S.A.R.','MAC','MO');
INSERT INTO countries(id,name,iso3,iso2) VALUES (129,'Macedonia','MKD','MK');
INSERT INTO countries(id,name,iso3,iso2) VALUES (130,'Madagascar','MDG','MG');
INSERT INTO countries(id,name,iso3,iso2) VALUES (131,'Malawi','MWI','MW');
INSERT INTO countries(id,name,iso3,iso2) VALUES (132,'Malaysia','MYS','MY');
INSERT INTO countries(id,name,iso3,iso2) VALUES (133,'Maldives','MDV','MV');
INSERT INTO countries(id,name,iso3,iso2) VALUES (134,'Mali','MLI','ML');
INSERT INTO countries(id,name,iso3,iso2) VALUES (135,'Malta','MLT','MT');
INSERT INTO countries(id,name,iso3,iso2) VALUES (137,'Marshall Islands','MHL','MH');
INSERT INTO countries(id,name,iso3,iso2) VALUES (138,'Martinique','MTQ','MQ');
INSERT INTO countries(id,name,iso3,iso2) VALUES (139,'Mauritania','MRT','MR');
INSERT INTO countries(id,name,iso3,iso2) VALUES (140,'Mauritius','MUS','MU');
INSERT INTO countries(id,name,iso3,iso2) VALUES (141,'Mayotte','MYT','YT');
INSERT INTO countries(id,name,iso3,iso2) VALUES (142,'Mexico','MEX','MX');
INSERT INTO countries(id,name,iso3,iso2) VALUES (143,'Micronesia','FSM','FM');
INSERT INTO countries(id,name,iso3,iso2) VALUES (144,'Moldova','MDA','MD');
INSERT INTO countries(id,name,iso3,iso2) VALUES (145,'Monaco','MCO','MC');
INSERT INTO countries(id,name,iso3,iso2) VALUES (146,'Mongolia','MNG','MN');
INSERT INTO countries(id,name,iso3,iso2) VALUES (147,'Montenegro','MNE','ME');
INSERT INTO countries(id,name,iso3,iso2) VALUES (149,'Morocco','MAR','MA');
INSERT INTO countries(id,name,iso3,iso2) VALUES (150,'Mozambique','MOZ','MZ');
INSERT INTO countries(id,name,iso3,iso2) VALUES (151,'Myanmar','MMR','MM');
INSERT INTO countries(id,name,iso3,iso2) VALUES (152,'Namibia','NAM','NA');
INSERT INTO countries(id,name,iso3,iso2) VALUES (153,'Nauru','NRU','NR');
INSERT INTO countries(id,name,iso3,iso2) VALUES (154,'Nepal','NPL','NP');
INSERT INTO countries(id,name,iso3,iso2) VALUES (156,'Netherlands','NLD','NL');
INSERT INTO countries(id,name,iso3,iso2) VALUES (157,'New Caledonia','NCL','NC');
INSERT INTO countries(id,name,iso3,iso2) VALUES (158,'New Zealand','NZL','NZ');
INSERT INTO countries(id,name,iso3,iso2) VALUES (159,'Nicaragua','NIC','NI');
INSERT INTO countries(id,name,iso3,iso2) VALUES (160,'Niger','NER','NE');
INSERT INTO countries(id,name,iso3,iso2) VALUES (161,'Nigeria','NGA','NG');
INSERT INTO countries(id,name,iso3,iso2) VALUES (162,'Niue','NIU','NU');
INSERT INTO countries(id,name,iso3,iso2) VALUES (163,'Norfolk Island','NFK','NF');
INSERT INTO countries(id,name,iso3,iso2) VALUES (115,'North Korea','PRK','KP');
INSERT INTO countries(id,name,iso3,iso2) VALUES (165,'Norway','NOR','NO');
INSERT INTO countries(id,name,iso3,iso2) VALUES (166,'Oman','OMN','OM');
INSERT INTO countries(id,name,iso3,iso2) VALUES (167,'Pakistan','PAK','PK');
INSERT INTO countries(id,name,iso3,iso2) VALUES (168,'Palau','PLW','PW');
INSERT INTO countries(id,name,iso3,iso2) VALUES (169,'Palestinian Territory Occupied','PSE','PS');
INSERT INTO countries(id,name,iso3,iso2) VALUES (170,'Panama','PAN','PA');
INSERT INTO countries(id,name,iso3,iso2) VALUES (171,'Papua new Guinea','PNG','PG');
INSERT INTO countries(id,name,iso3,iso2) VALUES (172,'Paraguay','PRY','PY');
INSERT INTO countries(id,name,iso3,iso2) VALUES (173,'Peru','PER','PE');
INSERT INTO countries(id,name,iso3,iso2) VALUES (174,'Philippines','PHL','PH');
INSERT INTO countries(id,name,iso3,iso2) VALUES (175,'Pitcairn Island','PCN','PN');
INSERT INTO countries(id,name,iso3,iso2) VALUES (176,'Poland','POL','PL');
INSERT INTO countries(id,name,iso3,iso2) VALUES (177,'Portugal','PRT','PT');
INSERT INTO countries(id,name,iso3,iso2) VALUES (179,'Qatar','QAT','QA');
INSERT INTO countries(id,name,iso3,iso2) VALUES (180,'Reunion','REU','RE');
INSERT INTO countries(id,name,iso3,iso2) VALUES (181,'Romania','ROU','RO');
INSERT INTO countries(id,name,iso3,iso2) VALUES (182,'Russia','RUS','RU');
INSERT INTO countries(id,name,iso3,iso2) VALUES (183,'Rwanda','RWA','RW');
INSERT INTO countries(id,name,iso3,iso2) VALUES (184,'Saint Helena','SHN','SH');
INSERT INTO countries(id,name,iso3,iso2) VALUES (187,'Saint Pierre and Miquelon','SPM','PM');
INSERT INTO countries(id,name,iso3,iso2) VALUES (189,'Saint-Barthelemy','BLM','BL');
INSERT INTO countries(id,name,iso3,iso2) VALUES (190,'Saint-Martin (French part)','MAF','MF');
INSERT INTO countries(id,name,iso3,iso2) VALUES (191,'Samoa','WSM','WS');
INSERT INTO countries(id,name,iso3,iso2) VALUES (192,'San Marino','SMR','SM');
INSERT INTO countries(id,name,iso3,iso2) VALUES (193,'Sao Tome and Principe','STP','ST');
INSERT INTO countries(id,name,iso3,iso2) VALUES (194,'Saudi Arabia','SAU','SA');
INSERT INTO countries(id,name,iso3,iso2) VALUES (195,'Senegal','SEN','SN');
INSERT INTO countries(id,name,iso3,iso2) VALUES (196,'Serbia','SRB','RS');
INSERT INTO countries(id,name,iso3,iso2) VALUES (197,'Seychelles','SYC','SC');
INSERT INTO countries(id,name,iso3,iso2) VALUES (198,'Sierra Leone','SLE','SL');
INSERT INTO countries(id,name,iso3,iso2) VALUES (199,'Singapore','SGP','SG');
INSERT INTO countries(id,name,iso3,iso2) VALUES (250,'Sint Maarten (Dutch part)','SXM','SX');
INSERT INTO countries(id,name,iso3,iso2) VALUES (200,'Slovakia','SVK','SK');
INSERT INTO countries(id,name,iso3,iso2) VALUES (201,'Slovenia','SVN','SI');
INSERT INTO countries(id,name,iso3,iso2) VALUES (202,'Solomon Islands','SLB','SB');
INSERT INTO countries(id,name,iso3,iso2) VALUES (203,'Somalia','SOM','SO');
INSERT INTO countries(id,name,iso3,iso2) VALUES (204,'South Africa','ZAF','ZA');
INSERT INTO countries(id,name,iso3,iso2) VALUES (205,'South Georgia','SGS','GS');
INSERT INTO countries(id,name,iso3,iso2) VALUES (116,'South Korea','KOR','KR');
INSERT INTO countries(id,name,iso3,iso2) VALUES (206,'South Sudan','SSD','SS');
INSERT INTO countries(id,name,iso3,iso2) VALUES (207,'Spain','ESP','ES');
INSERT INTO countries(id,name,iso3,iso2) VALUES (208,'Sri Lanka','LKA','LK');
INSERT INTO countries(id,name,iso3,iso2) VALUES (209,'Sudan','SDN','SD');
INSERT INTO countries(id,name,iso3,iso2) VALUES (210,'Suriname','SUR','SR');
INSERT INTO countries(id,name,iso3,iso2) VALUES (211,'Svalbard And Jan Mayen Islands','SJM','SJ');
INSERT INTO countries(id,name,iso3,iso2) VALUES (212,'Swaziland','SWZ','SZ');
INSERT INTO countries(id,name,iso3,iso2) VALUES (213,'Sweden','SWE','SE');
INSERT INTO countries(id,name,iso3,iso2) VALUES (214,'Switzerland','CHE','CH');
INSERT INTO countries(id,name,iso3,iso2) VALUES (215,'Syria','SYR','SY');
INSERT INTO countries(id,name,iso3,iso2) VALUES (216,'Taiwan','TWN','TW');
INSERT INTO countries(id,name,iso3,iso2) VALUES (217,'Tajikistan','TJK','TJ');
INSERT INTO countries(id,name,iso3,iso2) VALUES (218,'Tanzania','TZA','TZ');
INSERT INTO countries(id,name,iso3,iso2) VALUES (219,'Thailand','THA','TH');
INSERT INTO countries(id,name,iso3,iso2) VALUES (220,'Togo','TGO','TG');
INSERT INTO countries(id,name,iso3,iso2) VALUES (221,'Tokelau','TKL','TK');
INSERT INTO countries(id,name,iso3,iso2) VALUES (222,'Tonga','TON','TO');
INSERT INTO countries(id,name,iso3,iso2) VALUES (224,'Tunisia','TUN','TN');
INSERT INTO countries(id,name,iso3,iso2) VALUES (225,'Turkey','TUR','TR');
INSERT INTO countries(id,name,iso3,iso2) VALUES (226,'Turkmenistan','TKM','TM');
INSERT INTO countries(id,name,iso3,iso2) VALUES (228,'Tuvalu','TUV','TV');
INSERT INTO countries(id,name,iso3,iso2) VALUES (229,'Uganda','UGA','UG');
INSERT INTO countries(id,name,iso3,iso2) VALUES (230,'Ukraine','UKR','UA');
INSERT INTO countries(id,name,iso3,iso2) VALUES (231,'United Arab Emirates','ARE','AE');
INSERT INTO countries(id,name,iso3,iso2) VALUES (232,'United Kingdom','GBR','GB');
INSERT INTO countries(id,name,iso3,iso2) VALUES (233,'United States','USA','US');
INSERT INTO countries(id,name,iso3,iso2) VALUES (234,'United States Minor Outlying Islands','UMI','UM');
INSERT INTO countries(id,name,iso3,iso2) VALUES (235,'Uruguay','URY','UY');
INSERT INTO countries(id,name,iso3,iso2) VALUES (236,'Uzbekistan','UZB','UZ');
INSERT INTO countries(id,name,iso3,iso2) VALUES (237,'Vanuatu','VUT','VU');
INSERT INTO countries(id,name,iso3,iso2) VALUES (238,'Vatican City State (Holy See)','VAT','VA');
INSERT INTO countries(id,name,iso3,iso2) VALUES (239,'Venezuela','VEN','VE');
INSERT INTO countries(id,name,iso3,iso2) VALUES (240,'Vietnam','VNM','VN');
INSERT INTO countries(id,name,iso3,iso2) VALUES (243,'Wallis And Futuna Islands','WLF','WF');
INSERT INTO countries(id,name,iso3,iso2) VALUES (244,'Western Sahara','ESH','EH');
INSERT INTO countries(id,name,iso3,iso2) VALUES (245,'Yemen','YEM','YE');
INSERT INTO countries(id,name,iso3,iso2) VALUES (246,'Zambia','ZMB','ZM');
INSERT INTO countries(id,name,iso3,iso2) VALUES (247,'Zimbabwe','ZWE','ZW');
